apiVersion: apps/v1
kind: Deployment
metadata:
  name: yy-deployment
  labels:
    app: y-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: y-flask
  template:
    metadata:
      labels:
        app: y-flask
    spec:
      containers:
      - name: y-flask
        image: dbdudska113/flask_y:v3
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /country
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred
