apiVersion: apps/v1
kind: Deployment
metadata:
  name: yy-deployment
  labels:
    app: y-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: y-flask
  template:
    metadata:
      labels:
        app: y-flask
    spec:
      containers:
      - name: y-flask
        image: dbdudska113/flask_y
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
