apiVersion: v1
kind: Service
metadata:
  name: yy-deployment
spec:
  selector:
    app: y-flask
  ports:
  - name: http
    protocol: TCP
    nodePort: 31532
    port: 80
    targetPort: 5000
  type: NodePort